version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/aws/functions/delete-tweets"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/aws/functions/carbon"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
