[build]
  command = "make build"
  functions = "functions"
  publish = "site"
[build.environment]
  GO_IMPORT_PATH = "github.com/dje/darrineden.com"
[[redirects]]
  from = "/resume"
  to = "https://storage.cloud.google.com/darrineden/Darrin_Eden_Resume.docx"
